In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.makaan.com/bangalore-residential-property/buy-property-in-bangalore-city?page=2'
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47'
}
webpage = requests.get(url, headers=headers).text
    
soup = BeautifulSoup(webpage, 'lxml')

In [3]:
containers = soup.find_all('li', class_='cardholder')

In [5]:
final2 = pd.DataFrame()
for j in range (1501,2000):
    url = 'https://www.makaan.com/bangalore-residential-property/buy-property-in-bangalore-city?page={}'.format(j)
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47'
    }
    webpage = requests.get(url, headers=headers).text
    
    soup = BeautifulSoup(webpage, 'lxml')
    
    title = []
    price = []
    size = []
    price_per_sqft = []
    status = []

    title = [i.find('div', class_='title-line').text for i in containers]
    price = [i.find('td', class_='price').text for i in containers]
    price_per_sqft = [i.find('td', class_='lbl rate').text for i in containers]
    size = [i.find('td', class_='size').text for i in containers]
    status = [i.find('td', class_="val").text for i in containers]
    
    d = {'title':title, 'price':price, 'size':size, 'price_per_sqft':price_per_sqft, 'status':status}
    df = pd.DataFrame(d)
    final2 = final2.append(df)

In [6]:
final2

,title,price,size,price_per_sqft,status
0,3 BHK Apartment in Bavisha Meadows,50.65 L,1206,"4,200 / sq ft",Under Construction
1,3 BHK Apartment in United Projects Greencity U...,73.79 L,1440,"5,124 / sq ft",Under Construction
2,4 BHK Villa in Mana Daintree By Mana,3.11 Cr,3533,"8,830 / sq ft",Under Construction
3,5 BHK Independent House in Speckles Patio,1.72 Cr,3000,"5,750 / sq ft",Under Construction
4,1 BHK Apartment in Sairam Sai Gangothri Hill C...,31.5 L,590,"5,339 / sq ft",Under Construction
...,...,...,...,...,...
15,Residential Plot in Saroj Whispering Winds,32.3 L,2000,"1,615 / sq ft",New
16,3 BHK Apartment in Navami Landmaark,1.33 Cr,1641,"8,133 / sq ft",Under Construction
17,2 BHK Apartment in V Venture EVA,56.76 L,983,"5,780 / sq ft",Ready to move
18,3 BHK Apartment in Adithya Rica,69.43 L,1310,"5,300 / sq ft",Under Construction
19,3 BHK Apartment in SB Templetree,1.5 Cr,1770,"8,509 / sq ft",Under Construction

In [7]:
final2.to_excel('bangalore flat price 1501-2000.xlsx')